%% Exact linearization of the Simulink model model_sterowania2015a
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 8.5.1 and Simulink Control Design (TM) 4.2.
%
% Generated on: 04-Apr-2024 14:06:20

%% Specify the model name
model = 'model_sterowania2015a';

%% Specify the analysis I/Os
% Get the analysis I/Os from the model
io = getlinio(model);

%% Specify the operating point
% Use the snapshot times
op = [0 1];


%% Linearize the model
sys = linearize(model,io,op);

%% Plot the resulting linearization
step(sys)

