%% Exact linearization of the Simulink model plant_model_for_linearization
%
% This MATLAB script is the command line equivalent of the exact
% linearization tab in linear analysis tool with current settings.
% It produces the exact same linearization results as hitting the Linearize button.

% MATLAB(R) file generated by MATLAB(R) 8.5.1 and Simulink Control Design (TM) 4.2.
%
% Generated on: 11-Apr-2024 13:24:15

%% Specify the model name
model = 'plant_model_for_linearization';

%% Specify the analysis I/Os
% Use root level inports and outports in plant_model_for_linearization
% by passing no input argument to the linearize command for analysis I/Os

%% Specify the operating point
% Create the operating point variable op_trim3 using model initial condition as a starting point
op = operpoint('plant_model_for_linearization');
% Set the states in the model with different values than model initial condition
% State (3) - plant_model_for_linearization/Cintegrator
op.States(3).x = 1.275039359089427;
% Set the inputs in the model with different values than model initial condition
% Input (1) - plant_model_for_linearization/u
op.Inputs(1).u = 0.4547778821501982;

%% Linearize the model
sys = linearize(model,op);
A = sys.a;
A(4,1) = 1;
A = [A, zeros(4,1)];
B = sys.b;
B(4,1) = 0; 

%% Plot the resulting linearization
% step(sys)

%% Luenberger Observer
A_obs = A(1:3,1:3);
B_obs = B(1:3);
C_obs = [1 0 0; 0 0 1];

rank(obsv(A_obs,C_obs))

eig_val = 20*[-1, -1.1, -1.2];
L = transpose(place(transpose(A_obs),C_obs.',eig_val));
A_LC = A_obs - L*C_obs;
eig(A_LC)

%% Observator Luenbergera z rozszerzona przestrzenia stanu
C_obs_aug = [C_obs, [0,0;0,1]];
A_obs_aug = [A_obs, B_obs, zeros(3,1); zeros(2, 5)]
B_obs_aug = [B_obs;zeros(2,1)]

rank(obsv(A_obs_aug,C_obs_aug))

eig_val = 10*[-1, -1.1, -1.2, -1.3, -1.4];
L_aug = transpose(place(transpose(A_obs_aug),C_obs_aug.',eig_val));
A_LC_aug = A_obs_aug - L_aug*C_obs_aug
eig(A_LC_aug)

%%
% Q = diag([1000,100,10]);
Q = diag([1000,100,10,500]);
R = 1;

Ts = 0.001;
Kd = lqrd(A,B,Q,R,Ts)
Kc = lqr(A,B,Q,R)

z_ep = op.States(1).x;
i_ep = op.States(3).x;
u_ep = op.Inputs(1).u;
