function [fitresult, gof] = XD
y = [82, 79, 57, 56, 53, 43, 38, 38, 34, 33];
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'y=95.12exp(-0.15x) + 1.45exp(0.21x)' fit:
%      X Input: x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Apr-2024 22:01:14


%% Fit: 'y=95.12exp(-0.15x) + 1.45exp(0.21x)'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [12.0185937096522 -0.619227954077767 85.6907773231045 -0.107592266995879];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'y(x)=95.12exp(-0.15x) + 1.45exp(0.21x)' );
h = plot( fitresult, xData, yData );
legend( h, 'Data', 'y=95.12exp(-0.15x) + 1.45exp(0.21x)', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x (rank)', 'Interpreter', 'none' );
ylabel( 'y (level)', 'Interpreter', 'none' );
grid on


